name: docker test
on: push

jobs:
  testdocker:
    runs-on: ubuntu-latest
    steps:
      - name: Start docker-compose
        run: |
          cd docker
          docker compose up -d --build

      - name: Stop docker-compose
        if: always()
        run: |
          cd docker
          docker compose down
