name: docker test
on: push

jobs:
  testdocker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run ducker
        run: cd docker
      - name: test
        run: docker-compose up -d
